# Generated by Django 4.2.13 on 2024-07-07 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincome',
            options={'verbose_name': 'User income'},
        ),
    ]
