# Generated by Django 4.2.13 on 2024-07-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0002_alter_userincome_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincome',
            options={'verbose_name_plural': 'User incomes'},
        ),
    ]
